@MembershipPortal.API_HostAddress = http://localhost:5224

GET {{MembershipPortal.API_HostAddress}}/api/tax




###

Content-Type: application/json

{
    
}


###

POST {{MembershipPortal.API_HostAddress}}/api/product
Content-Type: application/json

{
 "ProductName":"efg",
 "Price":344
}

###

GET {{MembershipPortal.API_HostAddress}}/api/product

###

GET {{MembershipPortal.API_HostAddress}}/api/product/2

###

PUT {{MembershipPortal.API_HostAddress}}/api/product/2
Content-Type: application/json

{
 "Id":2,
 "ProductName":"fat",
 "Price":454
}
###

DELETE {{MembershipPortal.API_HostAddress}}/api/product/3

###

DELETE {{MembershipPortal.API_HostAddress}}/api/subscription/3

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

PUT {{MembershipPortal.API_HostAddress}}/api/subscription/2
Content-Type: application/json

{
  "id": 2,
    
    "productId": 1,
    "discountId": 2,
    "startDate": "0001-01-01T00:00:00",
    "expiryDate": "0001-01-01T00:00:00"
  
}

###
