@MembershipPortal.API_HostAddress = http://localhost:5224

GET {{MembershipPortal.API_HostAddress}}/api/tax/12345




###

Content-Type: application/json

{
    
}


###

POST {{MembershipPortal.API_HostAddress}}/api/product
Content-Type: application/json

{
 "ProductName":"efg",
 "Price":344
}

###

GET {{MembershipPortal.API_HostAddress}}/api/product

###

GET {{MembershipPortal.API_HostAddress}}/api/product/2

###

PUT {{MembershipPortal.API_HostAddress}}/api/product/2
Content-Type: application/json

{
 "Id":2,
 "ProductName":"fat",
 "Price":454
}
###

DELETE {{MembershipPortal.API_HostAddress}}/api/product/3

###

DELETE {{MembershipPortal.API_HostAddress}}/api/subscription/3

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

PUT {{MembershipPortal.API_HostAddress}}/api/subscription/2
Content-Type: application/json

{
    "id": 2,
    "productId": 1,
    "discountId": 2,
    "startDate": "0001-01-01T00:00:00",
    "expiryDate": "0001-01-01T00:00:00"
}

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

POST {{MembershipPortal.API_HostAddress}}/api/subscription
Content-Type: application/json

{
  "SubscriberId" : 2,
  "ProductId" : 6,
  "DiscountId" : 1,
  "TaxId" : 2
}

###

GET {{MembershipPortal.API_HostAddress}}/api/Product/2

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription/1

###

POST {{MembershipPortal.API_HostAddress}}/api/subscription
Content-Type: application/json

{
  "SubscriberId" : 1,
  "ProductId" : 6,
  "DiscountId" : 3,
  "TaxId" : 2
}

###

DELETE {{MembershipPortal.API_HostAddress}}/api/subscription/5

###

POST {{MembershipPortal.API_HostAddress}}/api/discount
Content-Type: application/json

{
  //CreateDiscountDTO
}

###

GET {{MembershipPortal.API_HostAddress}}/api/gender

###

DELETE {{MembershipPortal.API_HostAddress}}/api/gender/12

###

GET {{MembershipPortal.API_HostAddress}}/api/tax/1

###

POST {{MembershipPortal.API_HostAddress}}/api/tax
Content-Type: application/json

{
  "sgst": 10.00,
  "cgst": 10.00
}

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/12

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

POST {{MembershipPortal.API_HostAddress}}/api/subscription
Content-Type: application/json

{
  "subscriberId": 1,
  "productId": 6,
  "discountId": 3,
   "taxId": 2
}

###

GET {{MembershipPortal.API_HostAddress}}/api/tax

###

POST {{MembershipPortal.API_HostAddress}}/api/tax
Content-Type: application/json

{
  "SGST":9,
  "CGST":9

  
}

###

GET {{MembershipPortal.API_HostAddress}}/api/Product/

###

GET {{MembershipPortal.API_HostAddress}}/api/Subscription/

###

POST {{MembershipPortal.API_HostAddress}}/api/subscription
Content-Type: application/json

{
  "SubscriberId":4,
  "ProductId":3,
  "DiscountId":2,
  "TaxId":1

}

###

PUT {{MembershipPortal.API_HostAddress}}/api/tax/0
Content-Type: application/json

{
 

}

###

PUT {{MembershipPortal.API_HostAddress}}/api/subscription/1
Content-Type: application/json

{
  "id":1,
   "SubscriberId":5,
  "ProductId":3,
  "DiscountId":2,
  "TaxId":1
}

###

GET {{MembershipPortal.API_HostAddress}}/api/Product/{id}

###

GET {{MembershipPortal.API_HostAddress}}/api/user/search?find=1212121212

###

POST {{MembershipPortal.API_HostAddress}}/api/user/advancesearch
Content-Type: application/json

{     "id": 0,
    "firstName": "dikshaa",
    "lastName": "Ingle",
    "email": "",
    "password": "1212121212",
    "contactNumber": ""
}
###


###


###

GET {{MembershipPortal.API_HostAddress}}/api/user/search?find=123459

###

GET {{MembershipPortal.API_HostAddress}}/api/user

###

POST {{MembershipPortal.API_HostAddress}}/api/user/advancesearch
Content-Type: application/json

{
    "firstName": "Pooja",
    "lastName": "Bhise",
    "email": "pooja123@gmail.com",
    "password": "pooja123@gmail.com",
    "contactNumber": ""
}
###
"firstName": "Pooja",
    "lastName": "Bhise",
    "email": "123459",
    "password": "pooja123@gmail.com",
    "contactNumber": "pooja@123"
    {GetUserDTO { Id = 0, FirstName = Pooja, LastName = Bhise, 
    Email = pooja123@gmail.com, Password = pooja123@gmail.com, 
    ContactNumber = p }}

POST {{MembershipPortal.API_HostAddress}}/api/user/advancesearch
Content-Type: application/json

{
  
}

###
 string FirstName,
            [MaxLength(50)]
            [Required(ErrorMessage = "LastName is Required")]
            string LastName,
            [MaxLength(100)]
            [Required(ErrorMessage ="Email is Required")]
            string Email,
            [MaxLength(50)]
            [Required(ErrorMessage = "Password is Required")]
            string Password,
            string ContactNumber

GET {{MembershipPortal.API_HostAddress}}/api/gender

###

GET {{MembershipPortal.API_HostAddress}}/api/gender/search?find=Lap

###

GET {{MembershipPortal.API_HostAddress}}/api/gender/Laptop

###

GET {{MembershipPortal.API_HostAddress}}/api/user/search?find=string

###

GET {{MembershipPortal.API_HostAddress}}/api/gender/search?find=Lap

###

GET {{MembershipPortal.API_HostAddress}}/api/gender/search?search=Lap

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/search?search=female

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

GET {{MembershipPortal.API_HostAddress}}/api/tax

###

GET {{MembershipPortal.API_HostAddress}}/api/user

###

GET {{MembershipPortal.API_HostAddress}}/api/product/search?find=trainer

###

POST {{MembershipPortal.API_HostAddress}}/api/product/advancesearch
Content-Type: application/json

{
  "productName": "Trainer 1month",
    "price": 1000.00
}

###

POST {{MembershipPortal.API_HostAddress}}/api/gender
Content-Type: application/json

{
  "genderName" : "Female"
}

###

POST {{MembershipPortal.API_HostAddress}}/api/discount
Content-Type: application/json

{
  "discountCode" : "DIS#20",
  "discountAmount" : 20,
  "isDiscountInPercentage" : false
}

###

GET {{MembershipPortal.API_HostAddress}}/api/discount

###

GET {{MembershipPortal.API_HostAddress}}/api/tax

###

PUT {{MembershipPortal.API_HostAddress}}/api/tax/1
Content-Type: application/json

{
    "id" : 1,
    "stateName": "Maharashtra",
    "sgst": 10.00,
    "cgst": 10.00,
    "totalTax": 20.00
}

###

DELETE {{MembershipPortal.API_HostAddress}}/api/tax/0

###

DELETE {{MembershipPortal.API_HostAddress}}/api/tax/1

###

POST {{MembershipPortal.API_HostAddress}}/api/tax
Content-Type: application/json

{
  "stateName": "Rajasthan",
    "sgst": 12.00,
    "cgst": 10.00,
    "totalTax": 20.00
}

###

POST {{MembershipPortal.API_HostAddress}}/api/gender
Content-Type: application/json

{
  "genderName" : "Other"
}

###

POST {{MembershipPortal.API_HostAddress}}/api/product/paginated?page=1&pageSize=3
Content-Type: application/json

{
    "id": 0,
    "productName": "Cardio ",
    "price": 0
}

###

GET {{MembershipPortal.API_HostAddress}}/api/USER

###

POST {{MembershipPortal.API_HostAddress}}/api/user/paginated?page=1&pageSize=1
Content-Type: application/json

{
   "id": 0,
    "firstName": "",
    "lastName": "",
    "email": "",
    "password": "",
    "contactNumber": ""
}

###

POST {{MembershipPortal.API_HostAddress}}/api/subscriber/paginated?page=2&pageSize=1
Content-Type: application/json

{
   "id": 0,
    "firstName": "",
    "lastName": "",
    "contactNumber": "",
    "email": "",
    "genderId": 0
}

###

POST {{MembershipPortal.API_HostAddress}}/api/gender/paginated?page=1&pageSize=1
Content-Type: application/json

{
  "id":0,
  "genderName":""
}

###

GET {{MembershipPortal.API_HostAddress}}/api/discount

###

POST {{MembershipPortal.API_HostAddress}}/api/discount/paginated?page=1&pageSize=1
Content-Type: application/json

{
 "id": 0,
    "discountCode": "",
    "discountAmount": 0
    
}

###

GET {{MembershipPortal.API_HostAddress}}/api/product


###

DELETE {{MembershipPortal.API_HostAddress}}/api/subscription/3

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/sorting?sortColumn=mobileNumber&sortOrder=asc
###

POST {{MembershipPortal.API_HostAddress}}/api/subscriber/paginated?page=1&pageSize=0
Content-Type: application/json

{
  "id": 2,
    "firstName": "Elon",
    "lastName": "Musk",
    "contactNumber": "9988999000",
    "email": "elon@gmail.com",
    "genderId": 1
}


###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/paginatedsorting?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/paginatedsorting?page=0&pageSize=0&sortColumn=string&sortOrder=string

###

GET {{MembershipPortal.API_HostAddress}}/api/subscriber/paginatedsorting?page=1&pageSize=10&sortColumn=firstName&sortOrder=asc

###

POST {{MembershipPortal.API_HostAddress}}/api/subscriber/paginatedsorting?page=1&pageSize=10&sortColumn=firstName&sortOrder=desc
Content-Type: application/json

{
    "id": 0,
    "firstName": "",
    "lastName": "",
    "contactNumber": "",
    "email": "",
    "genderId": 0
}

###

POST {{MembershipPortal.API_HostAddress}}/api/subscriber/paginatedsorting?page=0&pageSize=0&sortColumn=string&sortOrder=string
Content-Type: application/json

{
    "id": 0,
    "firstName": "",
    "lastName": "Bhse",
    "contactNumber": "9988999000",
    "email": "email",
    "genderId": 10
}

###

GET {{MembershipPortal.API_HostAddress}}/api/discount

###

GET {{MembershipPortal.API_HostAddress}}/api/subscription

###

POST {{MembershipPortal.API_HostAddress}}/api/subscription/paginatedsorting?page=1&pageSize=10&sortColumn=taxAmount&sortOrder=asc
Content-Type: application/json

{
  "id": 0,
    "subscriberId": 0,
    "productId": 0,
    "productName": "",
    "productPrice": 0,
    "discountId": 0,
    "discountCode": "",
    "discountAmount": 0,
    "startDate": "2001-01-01",
    "expiryDate": "2001-01-01",
    "priceAfterDiscount": 0,
    "taxId": 0,
    "cgst": 0,
    "sgst": 0,
    "totalTaxPercentage": 0,
    "taxAmount": 0,
    "finalAmount": 0
}

###
