@MembershipPortal.API_HostAddress = http://localhost:5224

GET {{MembershipPortal.API_HostAddress}}/api/tax




###

Content-Type: application/json

{
}

###


###


###


###

POST {{MembershipPortal.API_HostAddress}}/api/product
Content-Type: application/json

{
 "ProductName":"cardio",
 "Price":34444
}

###

GET {{MembershipPortal.API_HostAddress}}/api/product

###
